import { useState, type Dispatch, type FormEvent, type KeyboardEvent, type RefObject, type SetStateAction } from "react";
import { ArrowLeft, ChatCircleDots, CheckCircle, DownloadSimple, Heart, Info, LockKey, Microphone, MicrophoneSlash, NotePencil, PaperPlaneTilt, Pause, PhoneDisconnect, Play, Pulse, ShieldCheck, Sparkle, Star, UserCircle, VideoCamera, VideoCameraSlash, Warning, WarningCircle, X } from "@phosphor-icons/react";
import type { SessionMatch } from "@bodhi/shared";
import { Button } from "../ui/Button";

export type SessionMessage = { id: string; body: string; sentAt: string; sender: string; own?: boolean };
type MatchContext = (SessionMatch & { mood?: string; urgent?: boolean }) | undefined;
type CommonProps = {
  sessionId: string; match: MatchContext; messages: SessionMessage[]; draft: string; setDraft: Dispatch<SetStateAction<string>>;
  paused: boolean; setPaused: Dispatch<SetStateAction<boolean>>; ended: boolean; toast: string; setToast: Dispatch<SetStateAction<string>>; time: string;
  bottom: RefObject<HTMLDivElement | null>; submit: (event: FormEvent) => void; handleKeys: (event: KeyboardEvent<HTMLTextAreaElement>) => void;
  endSession: () => void; saveTranscript: () => void; escalate: () => void; localVideo: RefObject<HTMLVideoElement | null>; remoteVideo: RefObject<HTMLVideoElement | null>;
  muted: boolean; cameraOff: boolean; toggleAudio: () => void; toggleVideo: () => void; mediaError: string;
};

const studentReplies = ["I'm feeling anxious", "I need a moment", "I'm not sure how to explain", "Can we talk more?", "Thank you for listening"];
const clinicianReplies = ["Take your time—I'm here.", "What feels most important right now?", "Would you like to pause?", "Can you tell me more about that?", "You did the right thing by reaching out."];

function Toast({ text, close }: { text: string; close: () => void }) { return text ? <div className="role-session-toast" role="status"><CheckCircle weight="fill" /><span>{text}</span><button onClick={close} aria-label="Dismiss"><X /></button></div> : null; }
function MessageList({ messages, bottom, emptyTitle, emptyBody, psychologist }: { messages: SessionMessage[]; bottom: CommonProps["bottom"]; emptyTitle: string; emptyBody: string; psychologist?: boolean }) {
  return <div className="role-chat__messages" aria-live="polite">
    {!messages.length && <div className="role-chat__empty"><span>{psychologist ? <ChatCircleDots weight="duotone" /> : <Heart weight="duotone" />}</span><h2>{emptyTitle}</h2><p>{emptyBody}</p><small><ShieldCheck weight="fill" /> Private, anonymous-facing session</small></div>}
    {messages.map(message => <div key={message.id} className={`role-message ${message.own ? "role-message--own" : ""}`}><div><p>{message.body}</p><small>{message.own ? "You" : psychologist ? "Student" : "Psychologist"} · {new Date(message.sentAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</small></div></div>)}
    <div ref={bottom} />
  </div>;
}
function Composer({ draft, setDraft, submit, handleKeys, replies, disabled, placeholder }: Pick<CommonProps, "draft" | "setDraft" | "submit" | "handleKeys"> & { replies: string[]; disabled: boolean; placeholder: string }) {
  return <div className="role-composer"><div className="role-composer__suggestions">{replies.map(reply => <button key={reply} type="button" onClick={() => setDraft(reply)} disabled={disabled}>{reply}</button>)}</div><form onSubmit={submit}><textarea rows={1} value={draft} onChange={event => setDraft(event.target.value)} onKeyDown={handleKeys} placeholder={disabled ? "This session has ended" : placeholder} disabled={disabled} maxLength={4000} /><span>{draft.length}/4000</span><Button disabled={disabled || !draft.trim()} aria-label="Send message"><PaperPlaneTilt weight="fill" /></Button></form><small>Enter to send · Shift + Enter for a new line</small></div>;
}
function CallStage(props: CommonProps & { psychologist?: boolean }) {
  return <div className={`role-call ${props.psychologist ? "role-call--clinician" : ""}`}><video ref={props.remoteVideo} autoPlay playsInline /><video className="role-call__local" ref={props.localVideo} autoPlay playsInline muted />{props.mediaError && <div className="role-call__error"><WarningCircle />{props.mediaError}</div>}<div className="role-call__identity"><span>{props.psychologist ? "Student" : "Psychologist"}</span><strong>{props.match?.peerLabel ?? (props.psychologist ? "Anonymous student" : "Bodhi-Mitra professional")}</strong></div><div className="role-call__controls"><button onClick={props.toggleAudio} aria-label={props.muted ? "Unmute" : "Mute"}>{props.muted ? <MicrophoneSlash /> : <Microphone />}</button>{props.match?.mode === "video" && <button onClick={props.toggleVideo} aria-label={props.cameraOff ? "Turn camera on" : "Turn camera off"}>{props.cameraOff ? <VideoCameraSlash /> : <VideoCamera />}</button>}<button className="end" onClick={props.endSession}><PhoneDisconnect /> End</button></div></div>;
}

export function StudentSessionView(props: CommonProps & { ratingOpen: boolean; rating: number; setRating: Dispatch<SetStateAction<number>>; submitRating: () => void; skipRating: () => void }) {
  return <section className="role-session role-session--student"><Toast text={props.toast} close={() => props.setToast("")} /><header className="student-session-head"><div className="student-session-head__identity"><span>{props.match?.peerLabel?.[0] ?? "P"}<i /></span><div><small>Your support session</small><strong>{props.match?.peerLabel ?? "Bodhi-Mitra psychologist"}</strong></div></div><div className="student-session-head__status"><span><LockKey weight="fill" /> Anonymous</span><b>{props.paused ? "Paused" : props.ended ? "Ended" : `Live · ${props.time}`}</b></div><div className="student-session-head__actions"><button onClick={props.escalate} className="safety"><WarningCircle /> I feel unsafe</button><button onClick={props.endSession} disabled={props.ended}><PhoneDisconnect /> End session</button></div></header>{props.paused && <div className="student-pause"><Pause weight="fill" /><div><strong>Take all the time you need.</strong><span>Your psychologist will know that you need a moment.</span></div><Button onClick={() => props.setPaused(false)}><Play weight="fill" /> Resume</Button></div>}<div className="student-session-layout"><aside className="student-care-rail"><div className="student-care-card"><Sparkle weight="fill" /><h2>This space is yours.</h2><p>Share only what feels comfortable. There is no pressure to find the perfect words.</p></div><button className="student-pause-button" onClick={() => props.setPaused(true)} disabled={props.paused || props.ended}><Pause /> I need a moment</button><div className="student-privacy-note"><ShieldCheck weight="duotone" /><div><strong>Your privacy</strong><p>Your identity is shielded from the psychologist during this session.</p></div></div></aside><main className="role-chat">{props.match?.mode && props.match.mode !== "chat" ? <CallStage {...props} /> : <><MessageList messages={props.messages} bottom={props.bottom} emptyTitle="You can begin whenever you're ready" emptyBody="Your psychologist is here. A short sentence is enough to start." /><Composer {...props} replies={studentReplies} disabled={props.ended} placeholder="Share what's on your mind…" /></>}</main></div>{props.ratingOpen && <div className="student-modal-backdrop"><div className="student-modal role-rating"><Star weight="duotone" /><span>Session complete</span><h2>How supported did you feel?</h2><p>Your feedback helps us improve student care.</p><div className="role-rating__stars">{[1,2,3,4,5].map(value => <button className={value <= props.rating ? "active" : ""} onClick={() => props.setRating(value)} key={value} aria-label={`${value} stars`}><Star weight={value <= props.rating ? "fill" : "regular"} /></button>)}</div><div className="role-rating__actions"><Button variant="secondary" onClick={props.skipRating}>Skip</Button><Button disabled={!props.rating} onClick={props.submitRating}>Submit feedback</Button></div></div></div>}</section>;
}

export function PsychologistSessionView(props: CommonProps & { onExit: () => void }) {
  const [notes, setNotes] = useState("");
  return <section className="role-session role-session--psychologist"><Toast text={props.toast} close={() => props.setToast("")} /><header className="clinician-session-head"><div><span className="clinician-live"><i /> {props.ended ? "Session ended" : "Active session"}</span><h1>Support workspace</h1><p>Session {props.sessionId.slice(0, 8)} · {props.time}</p></div><div className="clinician-session-head__actions"><button onClick={props.saveTranscript}><DownloadSimple /> Save locally</button><button onClick={props.escalate} className="escalate"><Warning /> Escalate safety</button>{props.ended ? <button className="end" onClick={props.onExit}><ArrowLeft /> Return to sessions</button> : <button className="end" onClick={props.endSession}><PhoneDisconnect /> End session</button>}</div></header><div className="clinician-layout"><aside className="clinician-context"><section><header><UserCircle weight="duotone" /><div><small>Anonymous student</small><strong>{props.match?.peerLabel ?? "Student identity shielded"}</strong></div></header><dl><div><dt>Mode</dt><dd>{props.match?.mode ?? "Chat"}</dd></div><div><dt>Shared mood</dt><dd>{props.match?.mood ?? "Not shared"}</dd></div><div><dt>Priority</dt><dd className={props.match?.urgent ? "urgent" : ""}>{props.match?.urgent ? "Urgent" : "Standard"}</dd></div></dl></section><section className="clinician-guidance"><Pulse weight="duotone" /><h2>Session guidance</h2><ul><li>Lead with validation and open questions.</li><li>Check immediate safety when appropriate.</li><li>Allow silence without rushing the student.</li></ul></section><section className="clinician-notes"><div><NotePencil /><h2>Private scratchpad</h2></div><textarea value={notes} onChange={event => setNotes(event.target.value)} rows={5} maxLength={1200} placeholder="Temporary notes for this conversation…" /><small><Info /> Not saved or transmitted. Cleared when you leave.</small></section></aside><main className="role-chat role-chat--clinician">{props.match?.mode && props.match.mode !== "chat" ? <CallStage {...props} psychologist /> : <><div className="clinician-chat-label"><div><ChatCircleDots /><span><strong>Live conversation</strong><small>Respond with care and clarity</small></span></div><span><ShieldCheck /> Verified professional</span></div><MessageList messages={props.messages} bottom={props.bottom} emptyTitle="The student has joined" emptyBody="Begin with a calm welcome and let them set the pace." psychologist /><Composer {...props} replies={clinicianReplies} disabled={props.ended} placeholder="Write a supportive response…" /></>}</main></div></section>;
}
