import compression from "compression";
import cors from "cors";
import express from "express";
import helmet from "helmet";
import morgan from "morgan";
import { env } from "./config/env.js";
import { errorHandler } from "./middleware/error.js";
import { api } from "./routes/index.js";
export const app = express();
app.set("trust proxy", 1); app.use(helmet()); app.use(cors({ origin: env.CLIENT_URL, credentials: true })); app.use(compression()); app.use(express.json({ limit: "32kb" })); app.use(morgan(env.NODE_ENV === "production" ? "combined" : "dev"));
app.use("/api", api); app.use((_req, res) => res.status(404).json({ message: "Route not found" })); app.use(errorHandler);
