import type { Request, Response } from "express";
import { AuditLog } from "../models/AuditLog.js";
import { EmergencyRequest } from "../models/EmergencyRequest.js";
import { Session } from "../models/Session.js";
import { User } from "../models/User.js";

export async function adminAnalytics(_req:Request,res:Response){const since=new Date(Date.now()-7*86400000);const [students,activeStudents,psychologists,online,totalRequests,pending,timeouts,matched,sessions,ratings,daily,statusMix,modeMix]=await Promise.all([User.countDocuments({role:"student"}),User.countDocuments({role:"student",isActive:true}),User.countDocuments({role:"psychologist"}),User.countDocuments({role:"psychologist",isOnline:true}),EmergencyRequest.countDocuments(),EmergencyRequest.countDocuments({status:"pending"}),EmergencyRequest.countDocuments({status:"timeout"}),EmergencyRequest.countDocuments({status:{$in:["matched","ended"]}}),Session.countDocuments(),Session.aggregate([{$match:{rating:{$exists:true}}},{$group:{_id:null,average:{$avg:"$rating"},count:{$sum:1}}}]),EmergencyRequest.aggregate([{$match:{createdAt:{$gte:since}}},{$group:{_id:{$dateToString:{format:"%Y-%m-%d",date:"$createdAt"}},count:{$sum:1}}},{$sort:{_id:1}}]),EmergencyRequest.aggregate([{$group:{_id:"$status",count:{$sum:1}}}]),EmergencyRequest.aggregate([{$group:{_id:"$mode",count:{$sum:1}}}])]);const waits=await EmergencyRequest.aggregate([{$match:{matchedAt:{$exists:true}}},{$project:{wait:{$subtract:["$matchedAt","$createdAt"]}}},{$group:{_id:null,average:{$avg:"$wait"},p95:{$max:"$wait"}}}]);res.json({analytics:{students,activeStudents,psychologists,onlinePsychologists:online,totalRequests,pendingRequests:pending,totalSessions:sessions,matchRate:totalRequests?Math.round(matched/totalRequests*100):0,timeoutRate:totalRequests?Math.round(timeouts/totalRequests*100):0,averageWaitSeconds:Math.round((waits[0]?.average??0)/1000),longestWaitSeconds:Math.round((waits[0]?.p95??0)/1000),averageRating:Number((ratings[0]?.average??0).toFixed(1)),ratingCount:ratings[0]?.count??0,dailyRequests:daily.map(x=>({date:x._id,count:x.count})),statusMix:statusMix.map(x=>({label:x._id,count:x.count})),modeMix:modeMix.map(x=>({label:x._id,count:x.count}))}})}
export async function adminStudents(req:Request,res:Response){const search=String(req.query.search??"").trim();const active=req.query.active;const filter:any={role:"student"};if(search)filter.$or=[{fullName:{$regex:search,$options:"i"}},{email:{$regex:search,$options:"i"}},{rollNumber:{$regex:search,$options:"i"}}];if(active==="true"||active==="false")filter.isActive=active==="true";const rows=await User.find(filter).select("fullName email rollNumber department verified isActive createdAt").sort({createdAt:-1}).limit(200);res.json({students:rows})}
export async function adminSessions(_req:Request,res:Response){const rows=await Session.find().select("sessionId mode startedAt endedAt rating psychologistId").populate("psychologistId","fullName").sort({startedAt:-1}).limit(200);res.json({sessions:rows})}
export async function adminReports(req:Request,res:Response){const status=String(req.query.status??"");const filter:any={action:{$in:["session.safety_escalated","session.feedback_low","psychologist.created","psychologist.updated"]}};if(status==="pending")filter["metadata.resolved"]={$ne:true};if(status==="resolved")filter["metadata.resolved"]=true;const rows=await AuditLog.find(filter).sort({createdAt:-1}).limit(200);res.json({reports:rows})}
export async function resolveReport(req:Request,res:Response){const row=await AuditLog.findByIdAndUpdate(req.params.id,{$set:{"metadata.resolved":true,"metadata.resolvedAt":new Date(),"metadata.resolvedBy":req.auth!.id}},{new:true});res.json({report:row})}
