import type { Request, Response } from "express";
import bcrypt from "bcryptjs";
import { psychologistSchema, specializations } from "@bodhi/shared";
import { AuditLog } from "../models/AuditLog.js";
import { EmergencyRequest } from "../models/EmergencyRequest.js";
import { Session } from "../models/Session.js";
import { User } from "../models/User.js";
import { saveSubscription } from "../services/push.service.js";

export async function studentHistory(req: Request, res: Response) { const rows = await EmergencyRequest.find({ studentId: req.auth!.id }).select("status mode createdAt matchedAt").sort({ createdAt: -1 }).limit(50); res.json({ requests: rows }); }
export async function psychologistQueue(_req: Request, res: Response) { const rows = await EmergencyRequest.find({ status: "pending", timeoutAt: { $gt: new Date() } }).select("anonId mode createdAt").sort({ createdAt: 1 }); res.json({ requests: rows.map(r => ({ requestId: r.id, anonId: r.anonId, mode: r.mode, waitStartedAt: r.createdAt })) }); }
export async function sessionHistory(req: Request, res: Response) { const rows = await Session.find({ psychologistId: req.auth!.id }).select("sessionId mode startedAt endedAt").sort({ startedAt: -1 }).limit(50); res.json({ sessions: rows }); }
export async function experts(_req: Request, res: Response) { const rows = await User.find({ role: "psychologist", verified: true, isActive: true }).select("fullName professionalTitle specializations"); res.json({ experts: rows }); }
export async function listPsychologists(_req: Request, res: Response) { const rows = await User.find({ role: "psychologist" }).select("fullName email professionalTitle specializations verified isActive isOnline mustChangePassword"); res.json({ psychologists: rows }); }
export async function createPsychologist(req: Request, res: Response) { const data = psychologistSchema.parse(req.body); if (!data.password) return res.status(400).json({ message: "An initial password is required" }); const passwordHash = await bcrypt.hash(data.password, 12); const user = await User.create({ role: "psychologist", fullName: data.name, email: data.email, passwordHash, professionalTitle: data.professionalTitle, specializations: data.specializations, verified: data.verified, isActive: data.isActive, mustChangePassword: true }); await AuditLog.create({ action: "psychologist.created", actorId: req.auth!.id, actorRole: "admin", targetType: "User", targetId: user.id }); res.status(201).json({ psychologist: user }); }
export async function updatePsychologist(req: Request, res: Response) { const data = psychologistSchema.partial().parse(req.body); const update: any = { ...data }; if (data.name) { update.fullName = data.name; delete update.name; } if (data.password) { update.passwordHash = await bcrypt.hash(data.password, 12); update.mustChangePassword = true; delete update.password; } const user = await User.findOneAndUpdate({ _id: req.params.id, role: "psychologist" }, update, { new: true, runValidators: true }); await AuditLog.create({ action: "psychologist.updated", actorId: req.auth!.id, actorRole: "admin", targetType: "User", targetId: req.params.id }); res.json({ psychologist: user }); }
export async function metrics(_req: Request, res: Response) { const [online, total, timedOut, matched, daily] = await Promise.all([User.countDocuments({ role: "psychologist", isOnline: true }), EmergencyRequest.countDocuments(), EmergencyRequest.countDocuments({ status: "timeout" }), EmergencyRequest.countDocuments({ status: { $in: ["matched", "ended"] } }), EmergencyRequest.countDocuments({ createdAt: { $gte: new Date(Date.now() - 86400000) } })]); const waits = await EmergencyRequest.aggregate([{ $match: { matchedAt: { $exists: true } } }, { $project: { wait: { $subtract: ["$matchedAt", "$createdAt"] } } }, { $group: { _id: null, average: { $avg: "$wait" } } }]); res.json({ metrics: { psychologistsOnline: online, requestsToday: daily, averageWaitSeconds: Math.round((waits[0]?.average ?? 0) / 1000), timeoutRate: total ? Math.round(timedOut / total * 100) : 0, matchedRequests: matched } }); }
export { specializations };
export async function subscribePush(req:Request,res:Response){await saveSubscription(req.auth!.id,req.body);res.status(201).json({message:"Notifications enabled"})}
