import { Router } from "express";
import rateLimit from "express-rate-limit";
import { me, passwordLogin, registerStudent, requestOtp, verifyOtp } from "../controllers/auth.controller.js";
import { createPsychologist, experts, listPsychologists, metrics, psychologistQueue, sessionHistory, studentHistory, subscribePush, updatePsychologist } from "../controllers/data.controller.js";
import { requireAuth } from "../middleware/auth.js";
import { adminAnalytics, adminReports, adminSessions, adminStudents, resolveReport } from "../controllers/admin.controller.js";
import { escalateSession, rateSession } from "../controllers/session.controller.js";
import { psychologistProfile, psychologistSummary, setAvailability } from "../controllers/psychologist.controller.js";
import { adminAssessments, assessmentStatus, submitAssessment } from "../controllers/assessment.controller.js";

export const api = Router();
const otpLimit = rateLimit({ windowMs: 10 * 60 * 1000, limit: 3, standardHeaders: true, legacyHeaders: false, message: { message: "Too many code requests. Please wait before trying again" } });
api.get("/health", (_req, res) => res.json({ status: "ok" }));
api.post("/auth/student/register", otpLimit, registerStudent);
api.post("/auth/student/request-otp", otpLimit, requestOtp);
api.post("/auth/student/verify-otp", verifyOtp);
api.post("/auth/login", rateLimit({ windowMs: 15 * 60 * 1000, limit: 10 }), passwordLogin);
api.get("/auth/me", requireAuth(), me);
api.get("/experts", experts);
api.get("/student/history", requireAuth(["student"]), studentHistory);
api.get("/student/assessment", requireAuth(["student"]), assessmentStatus);
api.post("/student/assessment", requireAuth(["student"]), submitAssessment);
api.get("/psychologist/queue", requireAuth(["psychologist"]), psychologistQueue);
api.get("/psychologist/sessions", requireAuth(["psychologist"]), sessionHistory);
api.get("/psychologist/summary", requireAuth(["psychologist"]), psychologistSummary);
api.get("/psychologist/profile", requireAuth(["psychologist"]), psychologistProfile);
api.patch("/psychologist/availability", requireAuth(["psychologist"]), setAvailability);
api.post("/psychologist/push-subscription", requireAuth(["psychologist"]), subscribePush);
api.get("/admin/psychologists", requireAuth(["admin"]), listPsychologists);
api.post("/admin/psychologists", requireAuth(["admin"]), createPsychologist);
api.patch("/admin/psychologists/:id", requireAuth(["admin"]), updatePsychologist);
api.get("/admin/metrics", requireAuth(["admin"]), metrics);
api.get("/admin/analytics", requireAuth(["admin"]), adminAnalytics);
api.get("/admin/students", requireAuth(["admin"]), adminStudents);
api.get("/admin/sessions", requireAuth(["admin"]), adminSessions);
api.get("/admin/reports", requireAuth(["admin"]), adminReports);
api.get("/admin/assessments", requireAuth(["admin"]), adminAssessments);
api.patch("/admin/reports/:id/resolve", requireAuth(["admin"]), resolveReport);
api.post("/sessions/:sessionId/rating", requireAuth(["student"]), rateSession);
api.post("/sessions/:sessionId/escalate", requireAuth(["student", "psychologist"]), escalateSession);
