import { GraduationCap, MagnifyingGlass, ShieldCheck, UserCircle, UsersThree } from "@phosphor-icons/react";
import { useEffect, useMemo, useState } from "react";
import { api } from "../../lib/api";
import directory from "../../data/psychologists.json";

type Category = "senior" | "consultant" | "trainee";
type Expert = { id: string; name: string; title: string; category: Category; image: string; specializations?: string[]; source?: "directory" | "admin" };
const labels: Record<Category, string> = { senior: "Senior", consultant: "Consultant", trainee: "Trainee" };
const order: Category[] = ["senior", "consultant", "trainee"];
const normalize = (value: string) => value.toLowerCase().replace(/^(dr|ms|mrs|mr)\.\s*/, "").replace(/\s+/g, " ").trim();

export function ExpertsDirectoryPage() {
  const [remote, setRemote] = useState<any[]>([]);
  const [filter, setFilter] = useState<"all" | Category>("all");
  const [search, setSearch] = useState("");
  const [apiAvailable, setApiAvailable] = useState(true);
  useEffect(() => { api<any>("/experts").then(result => setRemote(result.experts)).catch(() => setApiAvailable(false)); }, []);
  const experts = useMemo(() => { const merged = new Map<string, Expert>(); (directory as Expert[]).forEach(item => merged.set(normalize(item.name), { ...item, source: "directory" })); remote.forEach(row => { const key = normalize(row.fullName); const existing = merged.get(key); merged.set(key, { id: row._id, name: row.fullName, title: row.professionalTitle || "Psychologist", category: row.expertCategory || "consultant", image: row.portraitUrl || existing?.image || "/images/pschylogo.svg", specializations: row.specializations, source: "admin" }); }); return [...merged.values()]; }, [remote]);
  const shown = experts.filter(expert => (filter === "all" || expert.category === filter) && `${expert.name} ${expert.title} ${(expert.specializations || []).join(" ")}`.toLowerCase().includes(search.toLowerCase()));
  const counts = Object.fromEntries(order.map(category => [category, experts.filter(expert => expert.category === category).length])) as Record<Category, number>;
  return <div className="expert-directory"><header className="expert-directory__hero"><ShieldCheck weight="duotone"/><h1>Our Experts</h1><p>A verified community of mental health professionals supporting GBU students with care and confidentiality.</p></header><section className="expert-directory__controls"><label><MagnifyingGlass/><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search by name or specialization" aria-label="Search experts"/></label><div className="expert-filter" role="group" aria-label="Filter psychologist category"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>All <b>{experts.length}</b></button>{order.map(category=><button key={category} className={filter===category?"active":""} onClick={()=>setFilter(category)}>{labels[category]} <b>{counts[category]}</b></button>)}</div></section>{!apiAvailable&&<div className="expert-directory__notice">Showing the university directory. Live administrator additions will appear when the backend is running.</div>}<main>{order.map(category=>{const rows=shown.filter(expert=>expert.category===category);if(!rows.length)return null;const Icon=category==="senior"?GraduationCap:category==="consultant"?UsersThree:UserCircle;return <section className={`expert-group expert-group--${category}`} key={category}><header><Icon weight="duotone"/><div><h2>{labels[category]} Psychologists</h2><p>{category==="senior"?"Leadership and experienced clinical guidance.":category==="consultant"?"Qualified professionals providing psychological care.":"Psychologists developing practice under professional guidance."}</p></div><span>{rows.length}</span></header><div className="expert-cards">{rows.map(expert=><article key={expert.id}><div className="expert-photo"><img src={expert.image} alt={expert.name} onError={event=>{event.currentTarget.src="/images/pschylogo.svg"}}/>{expert.source==="admin"&&<ShieldCheck weight="fill"/>}</div><h3>{expert.name}</h3><p>{expert.title}</p>{expert.specializations?.length?<div>{expert.specializations.slice(0,3).map(value=><span key={value}>{value}</span>)}</div>:null}</article>)}</div></section>})}{!shown.length&&<div className="expert-directory__empty"><UserCircle/><h2>No experts match this filter</h2><p>Try another category or search term.</p></div>}</main><div className="expert-directory__trust"><ShieldCheck weight="fill"/><span><strong>Verified before publication</strong>Admin-created psychologists appear here only while their account is verified and active.</span></div></div>;
}
